(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 750,
	height: 1200,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/b01.png?1518317594125", id:"b01"},
		{src:"images/b02.png?1518317594125", id:"b02"},
		{src:"images/b03.png?1518317594125", id:"b03"},
		{src:"images/b05.png?1518317594125", id:"b05"},
		{src:"images/b06.png?1518317594125", id:"b06"},
		{src:"images/b07.png?1518317594125", id:"b07"},
		{src:"images/b08.png?1518317594125", id:"b08"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.b01 = function() {
	this.initialize(img.b01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,555,425);


(lib.b02 = function() {
	this.initialize(img.b02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,445,187);


(lib.b03 = function() {
	this.initialize(img.b03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,132,66);


(lib.b05 = function() {
	this.initialize(img.b05);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,204,204);


(lib.b06 = function() {
	this.initialize(img.b06);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,259,18);


(lib.b07 = function() {
	this.initialize(img.b07);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,113,293);


(lib.b08 = function() {
	this.initialize(img.b08);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,750,1200);


(lib.title = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1
	this.instance = new lib.b01();
	this.instance.setTransform(-255,-204);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-255,-204,555,425);


(lib.rule = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1
	this.instance = new lib.b07();
	this.instance.setTransform(-56.5,-146.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-56.5,-146.5,113,293);


(lib.shape35复制 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(255,255,204,0)","#FFFFCC","#FFFFCC"],[0.243,0.784,1],0,0,0,0,0,15.5).s().p("AgkCUIgBAAQgngKgfgeQgtgtAAg/QAAg+AtgtQAtgtA+AAQA1ABApAgIACACIAMAKQAsAtABA+QgBA/gsAtQgSARgVALIgCABQgeAPglABg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-15.3,-15.3,30.6,30.6);


(lib.glow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AshBXIAAitIZDAAIAACtg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.2,-8.8,160.6,17.6);


(lib.car2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1
	this.instance = new lib.b03();
	this.instance.setTransform(-66,-33);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-66,-33,132,66);


(lib.car1txt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1
	this.instance = new lib.b06();
	this.instance.setTransform(-129.5,-9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-129.5,-9,259,18);


(lib.car1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_6 = function() {
		this.gotoAndPlay(1);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(6).call(this.frame_6).wait(1));

	// 图层 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgIAlQAKAJAKACIADAiIAMgOIAkgBIgeAuIAmCMIAxgoIAWABIAfgiIiEiMIAJgIICICYQgqBZhNAugAiwi5IgJgMQAshCAlgeQAYgVAVgFIAVAbIAMB3IgYBGIAUAsIgNAKQhTg/gyhJgAiPjyIgeAzIBgBXIAHgaIggiYg");
	this.shape.setTransform(0.3,49.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjDDYIgHgQICcizIAaAUIAVAYIhWEQQhBgdgthcgAhRBrIhoBkIAjA4IAoApIAah9IBKhyIgbgVgAAnhBICXicIANAXIigCZIgEgUgAgFhzIBLjdQAMACAUAHIhMDqQgMgUgTgCg");
	this.shape_1.setTransform(-0.1,49.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},3).wait(3));

	// 图层 1
	this.instance = new lib.b02();
	this.instance.setTransform(-222.5,-93.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(7));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-222.5,-93.5,445,187);


(lib.c = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Am/XnMAAAgvOIN/AAMAAAAvOg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-44.8,-151.2,89.6,302.4);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 2
	this.instance = new lib.b08();
	this.instance.setTransform(-375,-600);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-375,-600,750,1200);


(lib.sprite36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Mask Layer 1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_3 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_4 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_5 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_6 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_7 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_8 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_9 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_10 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_11 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_12 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_13 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_14 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_15 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_16 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_17 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_18 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_19 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_20 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_21 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_22 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_23 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_28 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_29 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_30 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_31 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_32 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_33 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_34 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_35 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_36 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_37 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_38 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_39 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_40 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_41 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_42 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_43 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_44 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_45 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_46 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_47 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_48 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_49 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_53 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_54 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_55 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_56 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_57 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_58 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_59 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_60 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_61 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_62 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_63 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_64 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_65 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_66 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_67 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_68 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_69 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_70 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_71 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_72 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_73 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");
	var mask_graphics_74 = new cjs.Graphics().p("AAliVIACAAQhqO1ApPcQhExuCDsjgAD0KaQB9GdgXHaQgLnVhbmigACQifIACgBQHKIcCDP3Qipvammo4gAkMgtQn9HvkYHIQE6oZHbmegAWlJVQBSCDAxCSQg4iUhLiBgAhogmQkGGsg9HGQAlnsEemGgAI+CaQDnD2BoGwQiinmitjAgAEZjDQMkCsFoJsQlEoItIkQgAhMjqQufE+kaHlQFDpBN2jigAr6jPQn1A+kNEMQEdk2HlgUgAFTlEQLchjG8DlQnzi/qlA9gA4nmPQJVibN7DYQs9ipqTBsgAsRxjQIYBoDEJ7QkUpxnIhygACrmiQKdpWJ4DJQpAifrTIugAlE4TQHCFkh+L5QAbsOlflPgANm3cQnVgOlMQlQEDw2IeAfgADM6mQhsIcgXH8QAPrcB0k8gA00sgQGYg+DNCLQiqhdm7AQgAn6zRQFUDqA3DwQg9i3lOkjgASLx/QjvgXlaDvQFHkZECBBgAyHxvQDIgfCuArQiqghjMAVgAs377QEyAxDBC3QjEiakvhOg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(3).to({graphics:mask_graphics_3,x:-2.5,y:-9.1}).wait(1).to({graphics:mask_graphics_4,x:-2.5,y:-7.5}).wait(1).to({graphics:mask_graphics_5,x:-2.5,y:-5.9}).wait(1).to({graphics:mask_graphics_6,x:-2.5,y:-4.3}).wait(1).to({graphics:mask_graphics_7,x:-2.5,y:-2.7}).wait(1).to({graphics:mask_graphics_8,x:-2.5,y:-1.1}).wait(1).to({graphics:mask_graphics_9,x:-2.5,y:0.5}).wait(1).to({graphics:mask_graphics_10,x:-2.5,y:2.1}).wait(1).to({graphics:mask_graphics_11,x:-2.5,y:3.7}).wait(1).to({graphics:mask_graphics_12,x:-2.5,y:5.3}).wait(1).to({graphics:mask_graphics_13,x:-2.5,y:6.9}).wait(1).to({graphics:mask_graphics_14,x:-2.5,y:8.5}).wait(1).to({graphics:mask_graphics_15,x:-2.5,y:10.1}).wait(1).to({graphics:mask_graphics_16,x:-2.5,y:11.7}).wait(1).to({graphics:mask_graphics_17,x:-2.5,y:13.3}).wait(1).to({graphics:mask_graphics_18,x:-2.5,y:14.9}).wait(1).to({graphics:mask_graphics_19,x:-2.5,y:16.5}).wait(1).to({graphics:mask_graphics_20,x:-2.5,y:18.1}).wait(1).to({graphics:mask_graphics_21,x:-2.5,y:19.7}).wait(1).to({graphics:mask_graphics_22,x:-2.5,y:21.3}).wait(1).to({graphics:mask_graphics_23,x:-2.5,y:22.9}).wait(1).to({graphics:null,x:0,y:0}).wait(4).to({graphics:mask_graphics_28,x:53.5,y:-9.1}).wait(1).to({graphics:mask_graphics_29,x:53.4,y:-7.6}).wait(1).to({graphics:mask_graphics_30,x:53.2,y:-6.1}).wait(1).to({graphics:mask_graphics_31,x:53.1,y:-4.6}).wait(1).to({graphics:mask_graphics_32,x:53,y:-3}).wait(1).to({graphics:mask_graphics_33,x:52.8,y:-1.5}).wait(1).to({graphics:mask_graphics_34,x:52.7,y:0}).wait(1).to({graphics:mask_graphics_35,x:52.5,y:1.5}).wait(1).to({graphics:mask_graphics_36,x:52.4,y:3.1}).wait(1).to({graphics:mask_graphics_37,x:52.2,y:4.6}).wait(1).to({graphics:mask_graphics_38,x:52.1,y:6.1}).wait(1).to({graphics:mask_graphics_39,x:52,y:7.6}).wait(1).to({graphics:mask_graphics_40,x:51.8,y:9.2}).wait(1).to({graphics:mask_graphics_41,x:51.7,y:10.7}).wait(1).to({graphics:mask_graphics_42,x:51.5,y:12.2}).wait(1).to({graphics:mask_graphics_43,x:51.4,y:13.7}).wait(1).to({graphics:mask_graphics_44,x:51.2,y:15.3}).wait(1).to({graphics:mask_graphics_45,x:51.1,y:16.8}).wait(1).to({graphics:mask_graphics_46,x:51,y:18.3}).wait(1).to({graphics:mask_graphics_47,x:50.8,y:19.8}).wait(1).to({graphics:mask_graphics_48,x:50.7,y:21.4}).wait(1).to({graphics:mask_graphics_49,x:50.5,y:22.9}).wait(1).to({graphics:null,x:0,y:0}).wait(3).to({graphics:mask_graphics_53,x:-88.5,y:-9.1}).wait(1).to({graphics:mask_graphics_54,x:-88.4,y:-7.6}).wait(1).to({graphics:mask_graphics_55,x:-88.4,y:-6.1}).wait(1).to({graphics:mask_graphics_56,x:-88.3,y:-4.6}).wait(1).to({graphics:mask_graphics_57,x:-88.3,y:-3}).wait(1).to({graphics:mask_graphics_58,x:-88.2,y:-1.5}).wait(1).to({graphics:mask_graphics_59,x:-88.2,y:0}).wait(1).to({graphics:mask_graphics_60,x:-88.1,y:1.5}).wait(1).to({graphics:mask_graphics_61,x:-88.1,y:3.1}).wait(1).to({graphics:mask_graphics_62,x:-88,y:4.6}).wait(1).to({graphics:mask_graphics_63,x:-88,y:6.1}).wait(1).to({graphics:mask_graphics_64,x:-88,y:7.6}).wait(1).to({graphics:mask_graphics_65,x:-87.9,y:9.2}).wait(1).to({graphics:mask_graphics_66,x:-87.9,y:10.7}).wait(1).to({graphics:mask_graphics_67,x:-87.8,y:12.2}).wait(1).to({graphics:mask_graphics_68,x:-87.8,y:13.7}).wait(1).to({graphics:mask_graphics_69,x:-87.7,y:15.3}).wait(1).to({graphics:mask_graphics_70,x:-87.7,y:16.8}).wait(1).to({graphics:mask_graphics_71,x:-87.6,y:18.3}).wait(1).to({graphics:mask_graphics_72,x:-87.6,y:19.8}).wait(1).to({graphics:mask_graphics_73,x:-87.5,y:21.4}).wait(1).to({graphics:mask_graphics_74,x:-87.5,y:22.9}).wait(1));

	// Masked Layer 2 - 1
	this.instance = new lib.shape35复制("synched",0);
	this.instance.setTransform(2.7,-39.5);
	this.instance._off = true;

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(3).to({_off:false},0).to({scaleX:19.86,scaleY:19.86,y:-9.5},20).to({_off:true},1).wait(4).to({_off:false,scaleX:1,scaleY:1,x:58.7,y:-39.5},0).to({scaleX:19.86,scaleY:19.86,x:55.7,y:-9.5},21).to({_off:true},1).wait(3).to({_off:false,scaleX:1,scaleY:1,x:-83.3,y:-39.5},0).to({scaleX:19.86,scaleY:19.86,x:-82.3,y:-9.5},21).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.m = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Am9G+Qi4i5AAkFQAAkEC4i5QC5i4EEAAQEFAAC5C4QC4C5AAEEQAAEFi4C5Qi5C4kFAAQkEAAi5i4gAmnmnQixCwAAD3QAAD4CxCwQCwCxD3AAQD4AACwixQCxiwAAj4QAAj3ixiwQiwixj4AAIAAAAQj3AAiwCxgAAwERIADgFIAvACQAMAAACgMIACgJIh1AAIABgHIB1AAIACgSIhrAAIACgHIBqAAIADgRQg9ADgiAAIAAgFQB9gTAtgTIAgAWQADADAAADQgCAGgIAAIgNgCQgRAEgaABIgDAUIA4AAIATgWIAaAWQAEADgCACQgDACgFAAIgGAAIAVARQAFADgCACQgBADgIAAIhtAAIgDAUQgCAgg/AGQAJgagygIgACgDmIgCAMIBDAAIAQgSIhQAAgAhhDwIAIguIAOhcIAJhAIAyAEQAIAAAAAEQgCAHgMAEIgVCEIgHAqIgJBAQAAAHgFABIgPABIgdACIALhCgAkWEIIABgGIA5ADQAQACAEgPQAHgYAFgjIgtAAIgUAUQgUgNgNgNQgEgEAFgEQAIgCAFgKQAIgZAIgiIAtAOIAhAAIAIg2IhZAAIABgHIBVAAIAPgWIAqASQAEABgCADQgBAGgNAJIgCAOIgFAtQgBAGgIABQgJADgbACIgCAAIADgSIgkAAIgVA5IAuAAIAQgYIAsASQAFADgBADQgBAFgPAKQgDAXgLApQgIAohGAFQAIggg0gKgABkChQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAQgMACgLAAIACgLIgPAAIgBAGQAAAHgLACQgIACgOAAIAHgpIgQALIgLAFIgCgCQAbghAKggIAPACIACgKIghAAIAAgIIAiAAIADgYIAoACQABAAAAAAQABAAAAABQABAAAAABQAAABAAABQgCAFgHADIgCAKIAMAAIAEgaIAmAEQABAAABAAQABAAAAABQABAAAAAAQAAABAAABQgCAFgJAEIgCAKIAKAAIAMgPIAUAPQABABABABQABAAAAABQAAAAAAABQAAAAAAABQgEACgEABIgmAAIgBAFQAAABAAABQAAABAAAAQAAABgBAAQAAABgBAAIAgANQADACgBADQAAAEgLAGQgCARgHAYQgFAcgqADQACgNgGgGgAByB0QABABAAAAQABAAAAABQABAAAAABQAAAAAAABQAAAEgJAHIgEAVIAHAAQAFAAABgHQAGgSAEgZIg7AAIgHAHIgJAHIAQAEIALAAIAKgOgAA+CTIAQAAIADgWIgPAAgADYCTQgXAMgwAMIgCgDQAjgTAZgWQgGgLgBgSQgQAPgSAMIgDgBQARgeAKgYQAGgLAFgTIAAgEIAsAKQAEAAgBAEQgBAGgNADIgLANIApAAIARgUIAaAVQAAAAABABQABAAAAAAQAAABAAAAQAAABAAABQgCACgFAAIgRAAQgOAagTAUQARAGAfACIgBAEQgPAIgRAfQgggOgPgPgADMBaIARATQALgOAIgQIgZAAIgLALgABHglQBehDAPh2IgbAAIAAgHIAcAAIACgHIACgGIACgQIAEguIA3AFQAHAAgCADQgBAHgPAGIgFAjIgDATIANAAIASgZIAoATQAFACgBAEQgBAHgOAIQgKBBgNA9QgGAthDAGQAGgdgkgMIACgEIAkACQARAAAGgTQANg5AKhCIgUAAQgSCQiFAtgAhkg+IhaAAIgDANQgBAKgMABQgTACgRAAQAGgcAEggIAHgqQgUA0hEAsIgEgDQAegoANgiQANgiAKg9IABgNIAHgvIA2ANIAnAAQgHgCAAgLQgBgWgFgJIABgCQA7gCgEAaQgEARgUAFIAuAAIARgZIAqATQAGACAAAEQgCAHgNAJIgBADIgCANIgFAnQAAAHgKACQgUADgTAAIACgNIh2AAQgEARgFAPIAvAKIBOAAIAQgXIAsAUQAFADgBADQgBAHgPAJIgFAbIgGA2QgBAJgIAAQgTADgWABgAi9hEIBaAAIAKhKIhaAAgAjMjdIgDAWIB2AAIAIg3Ih1AAgAARhKIgJguQAQgEAJgPQAQgcAIgeIgnAAIABgIIBeAAIAWgYIAeAXQADAEgBACQgEADgFAAIgxAAQgXAkgoAmIA1gEQAAgLgGgTIgCgFIAEgDQA1AWgFAZQgHAZgWADQgOABAAgOIAAgJQgmARgeALQgEAPgIAAQgDAAAAgFgAAskDIABgIIBAAAIAWgXIAbAXQAEACgDAEQgBADgHgBg");

	// 图层 2
	this.instance = new lib.glow();
	this.instance.setTransform(46.6,-57.7,1,1,30,0,0,-0.1,-0.1);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-46.8,y:57.5},19,cjs.Ease.get(1)).wait(6));

	// 图层 3
	this.instance_1 = new lib.glow();
	this.instance_1.setTransform(46.6,-57.7,1,1,30,0,0,-0.1,-0.1);
	this.instance_1._off = true;

	this.instance_1.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(5).to({_off:false},0).to({x:-46.8,y:57.5},19,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-27.2,-63.1,90.3,53.3);


(lib.cm = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A2RGUQDHkcOUhZIA8gFQE7i/GmjFQFAhKJxAIIADADQoPAClHBDQmLDEkQDOIEZAVImBAvQjVAZizAfIMKhEIJsgMQmLAfpSCHIIViGQlVAJlhAfIkSAMQo1BjjbCWIgqAHg");

	// 图层 2
	this.instance = new lib.c();
	this.instance.setTransform(-161.4,96.8,1,1,-90.9);
	this.instance.alpha = 0.5;

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:-77.9,x:210.6,y:-88.4,alpha:0.199},20,cjs.Ease.get(-1)).wait(20));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 3
	this.instance = new lib.m();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(25));

	// 图层 1
	this.instance_1 = new lib.b05();
	this.instance_1.setTransform(-102,-102);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(25));

	// 图层 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D9BE95").s().p("AgjBYQgbAAAAgaIAAhSQgJAMgLAJQgEgFgFgGQAggjAQgqIAOAEIgIATIBpAAQgBBAgCAaQgDAegbAAIgbgBIgDgPIAbACQARAAABgSQADgYAAgzIhhAAIgOAXIBMAAIAAA1IhCAAIAAAiQAAAPAPAAIBVAAQASAAADgLQADgLABgRIAPAGQgCAQgDALQgEAUgcAAgAgwALIAzAAIAAgaIgzAAg");
	this.shape.setTransform(66,102.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D9BE95").s().p("AgdBWIAAgPIA1AAIAAh8IgqAAIAAgOIBmAAIAAAOIgtAAIAAB8IA1AAIAAAPgAhaBBIBGgPIgBAOIhBAQgAhYAbQAPgPAQgUIgdACIgEgNQAVgbASgnIAPAGQgTAhgRAaIAXgBIAPgYIAOAGQgYAmgXAZIAvgHIgCAPIg/AJg");
	this.shape_1.setTransform(47.1,102.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#D9BE95").s().p("AAvBSQgPgNgJgZQgVAQgYAMIgKgMQAegNAUgRQgFgUgDgfIghAEIgCgOIAjgEIgDg2IAQAAIABA0IA/gHIABANIg/AIQABAaAFASQAWgSAPgUIAMAJQgUAXgZAVQAHAWANALQAHAGAFAAQAEAAACgJIAFgdIAOAGQgEAVgDALQgEAPgNAAQgLAAgKgIgAhTBYIgDgPIAUABQAIAAAAgIIAAgyIgeAGIgDgPIAhgFIAAgqIgeAAIAAgNIAeAAIAAgjIAOAAIAAAjIAbAAIAAANIgbAAIAAAoIAbgEIABAMIgcAFIAAA4QAAATgSABIgVgBgAAihLIAJgJQAQALAPAMIgJALQgPgOgQgLg");
	this.shape_2.setTransform(28,102.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#D9BE95").s().p("AAABUIgBgQIAbACQAMAAAAgOIAAgdIiBAAIAAgNICBAAIAAgNIAQAAIAAANIAmAAIAAANIgmAAIAAAjQAAAXgYAAIgegBgAg4ApIAKgKIAfAbIgKAKIgfgbgAA4gBIAAgGIiCAAIAAgNICCAAIAAgTIh7AAIAAgNIB7AAIAAgTIiAAAIAAgNICOAAIAABTg");
	this.shape_3.setTransform(9,103.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#D9BE95").s().p("AhKBZIAAiRIBEAAIAAggIANAAIAAAgIBEAAIAAB4QAAAYgXgBIgeAAIgDgQIAeACQALAAAAgMIAAhnIg1AAQgBARgDANQAhAYAUAUIgLAMQgUgWgZgWQgMAagkAVIgKgOQAegQALgRQAJgPACgbIg1AAIAACDg");
	this.shape_4.setTransform(-10,103);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#D9BE95").s().p("AAABcIAAgnIhYAAIAAgOIBYAAIAAggIhCAAIAAgLIAXgsIgmAAIAAgOIAtAAIANgdIAOAEIgLAZIBmAAIAAAOIhtAAQgMAZgLATIAyAAIAAgkIAPAAIAAAkIA2AAIAAALIg2AAIAAAgIBKAAIAAAOIhKAAIAAAng");
	this.shape_5.setTransform(-29.1,102.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#D9BE95").s().p("Ag+BbIAAhOQgKANgMAJIgHgQQAegVAVgmIAOAHQgKAQgLAOIAABegAgiBRIAAgNIA3AAIAAg2IgqAAIAAgNIAqAAIAAgqIgwAAIAAgNIBxAAIAAANIgxAAIAAAqIAsAAIAAANIgsAAIAAA2IA3AAIAAANgAhagkQAbgVASgfIANAIQgWAjgdAWIgHgNgAAJhTIAMgHQALAMAHAMIgNAIQgIgNgJgMg");
	this.shape_6.setTransform(-48,102.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#D9BE95").s().p("AhNBcIAAh6IBPAAIAABlQAAATgRgBIgVAAIgDgNIAVAAQAIABAAgJIAAgXIg1AAIAAAvgAg/AgIA1AAIAAgTIg1AAgAg/AAIA1AAIAAgSIg1AAgAAfBYIgDgPIAXACQAMAAAAgNIAAhiIAOAAIAABmQAAAWgWAAIgLABIgNgBgAAYA2IAAhRIAOAAIAABRgAhZgwIAAgOIA8AAQgGgJgKgMIAMgHQALANAHAKIgJAFIAxAAIgIgDQAKgNAIgNIAOAIQgJAMgJAJIA7AAIAAAOg");
	this.shape_7.setTransform(-67,102.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(25));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-108,-105.2,228.6,221.8);


// stage content:
(lib.cover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_16 = function() {
		bodycolorChange();
	}
	this.frame_35 = function() {
		this.car1.gotoAndStop(0);
	}
	this.frame_56 = function() {
		this.btn.addEventListener("click",p1btnFunc);
	}
	this.frame_66 = function() {
		this.rule.addEventListener("click",ruleFunc);
	}
	this.frame_68 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(16).call(this.frame_16).wait(19).call(this.frame_35).wait(21).call(this.frame_56).wait(10).call(this.frame_66).wait(2).call(this.frame_68).wait(1));

	// regular
	this.rule = new lib.rule();
	this.rule.setTransform(-63.5,652.5);
	this.rule.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.rule).wait(56).to({x:56.5,alpha:1},10,cjs.Ease.get(1)).wait(3));

	// btn
	this.btn = new lib.btn();
	this.btn.setTransform(374,998);
	this.btn.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.btn).wait(49).to({scaleX:1.64,scaleY:1.64},0).to({scaleX:1,scaleY:1,alpha:1},7,cjs.Ease.get(-1)).wait(13));

	// car2
	this.instance = new lib.car2();
	this.instance.setTransform(-71.8,835.2,1.088,1.088);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(29).to({_off:false},0).to({scaleX:1,scaleY:1,x:129,y:816},17,cjs.Ease.get(0.6)).wait(23));

	// car1txt
	this.instance_1 = new lib.car1txt();
	this.instance_1.setTransform(730.5,926);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(36).to({_off:false},0).to({x:573.7,alpha:1},8,cjs.Ease.get(1)).wait(1).to({x:574},0).wait(1).to({x:574.9},0).wait(1).to({x:576.2},0).wait(1).to({x:577.4},0).wait(1).to({x:578.2},0).wait(1).to({x:578.5},0).wait(19));

	// ca1glow
	this.instance_2 = new lib.cm();
	this.instance_2.setTransform(389.6,757.8);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(38).to({_off:false},0).wait(31));

	// car1
	this.car1 = new lib.car1();
	this.car1.setTransform(540.8,798,0.2,0.2,0,-2.7,177.3,-0.3,0.5);
	this.car1.alpha = 0;
	this.car1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.car1).wait(1).to({_off:false},0).to({regX:0,regY:0.3,scaleX:0.57,scaleY:0.57,skewX:0,skewY:180,guide:{path:[540.8,797.8,702.3,804.3,863.9,819.9,854.1,819.4,844.4,818.9]},alpha:1},13,cjs.Ease.get(-0.5)).to({regX:-0.1,regY:0.5,scaleX:0.59,scaleY:0.59,skewY:0,guide:{path:[844.3,819,839.6,818.7,834.9,818.5]}},1).to({regX:0,regY:0,scaleX:1,scaleY:1,guide:{path:[834.9,818.4,806.7,816.7,780.2,814,740.3,810,641.4,811.4,542.5,812.8,461.4,807.5]}},20,cjs.Ease.get(0.5)).wait(34));

	// title
	this.instance_3 = new lib.title();
	this.instance_3.setTransform(349.5,386,0.127,0.127);
	this.instance_3.alpha = 0.199;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(38).to({_off:false},0).to({scaleX:1,scaleY:1,alpha:1},16,cjs.Ease.get(1)).wait(15));

	// firework
	this.instance_4 = new lib.sprite36();
	this.instance_4.setTransform(339.6,257.6);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(29).to({_off:false},0).wait(40));

	// bg
	this.instance_5 = new lib.bg();
	this.instance_5.setTransform(375,600);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(16).to({_off:false},0).to({alpha:1},25).wait(28));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(255,600,870,1200);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;